# Generated by Django 3.1.7 on 2021-03-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '코다 게시판', 'verbose_name_plural': '코다 게시판'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='community',
        ),
    ]
